<?php
$allTask = $this-> allTask;
?>
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Tabla de tareas</title>
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.css"  rel="stylesheet" />
</head>
<body>
<section class="bg-center bg-no-repeat bg-[url('https://flowbite.s3.amazonaws.com/docs/jumbotron/conference.jpg')] bg-gray-700 bg-blend-multiply">
    <div class="px-4 mx-auto max-w-screen-xl text-center py-24 lg:py-56">
        <h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl">Tabla de tareas</h1>
        <p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48">Crea y gestiona las tareas de tu evento</p>
        <div class="flex flex-col space-y-4 sm:flex-row sm:justify-center sm:space-y-0">
            <span class="flex items-center text-2xl font-bold text-white dark:text-white me-3"><span class="flex w-2.5 h-2.5 bg-blue-600 rounded-full me-1.5 flex-shrink-0"></span>
            <a href="<?php echo WEB_ROOT ?>/create"> Crear </a> </span>
            <span class="flex items-center text-2xl font-bold text-white dark:text-white me-3"><span class="flex w-2.5 h-2.5 bg-purple-500 rounded-full me-1.5 flex-shrink-0"></span>
            <a href="<?php echo WEB_ROOT ?>/updateId"> Editar </a> </span>
            <span class="flex items-center text-2xl font-bold text-white dark:text-white me-3"><span class="flex w-2.5 h-2.5 bg-indigo-500 rounded-full me-1.5 flex-shrink-0"></span>
            <a href="<?php echo WEB_ROOT ?>/delete"> Eliminar </a> </span>
            
</div> 
  
<table id="default-table" class="table-auto border-collapse bg-white rounded-lg shadow-lg mx-auto mt-4">
<thead>
                    <tr class="bg-gray-200">
                    <th class="px-4 py-2">ID</th>
                    <th class="px-4 py-2">Título</th>
                    <th class="px-4 py-2">Estado</th>
                    <th class="px-4 py-2">Fecha de inicio</th>
                    <th class="px-4 py-2">Fecha límite</th>
                    <th class="px-4 py-2">Usuario</th>
                </tr>
            </thead>
            <tbody>
            <?php foreach ($allTask as $task): ?>
                <tr>
                <td class="px-6 py-4 whitespace-nowrap text-black"><?php echo htmlspecialchars($task['id']); ?></td>    
                <td class="px-6 py-4 whitespace-nowrap text-black"><?php echo htmlspecialchars($task['title']); ?></td>
                <td class="px-6 py-4 whitespace-nowrap text-black"><?php echo htmlspecialchars($task['status']); ?></td>
                <td class="px-6 py-4 whitespace-nowrap text-black"><?php echo htmlspecialchars($task['starTime']); ?></td>
                <td class="px-6 py-4 whitespace-nowrap text-black"><?php echo htmlspecialchars($task['deadLine']); ?></td>
                <td class="px-6 py-4 whitespace-nowrap text-black"><?php echo htmlspecialchars($task['user']); ?></td>
                </tr>
                <?php endforeach; ?>
        
    </tbody>
</table>

        
    </div>
</section>

  
</body>
</html>