<section class="bg-[#BFE3F9]">
        <script src="https://cdn.tailwindcss.com"></script>

  
    <aside class="fixed top-0 left-0 h-screen w-80 bg-gradient-to-b from-[#BFE3F9] via-[#9ACCE6] to-[#6097BA]">
        <h1 class="font-sans text-2xl font-semibold text-black text-center mt-10 border-b-4 border-black pb-2">
             List of Tasks
        </h1>   
    </aside>
    
    <main class="ml-[22rem] min-h-screen border-4 border-[#BFE3F9] rounded-lg m-6 p-2 bg-white">
        <div class="px-8 py-6">
            <?php if (is_array($this->tasks) && count($this->tasks) > 0): ?>
                <div class="space-y-4">
                    <?php foreach ($this->tasks as $task): ?>
                        <div class="flex items-center justify-between border-b border-black pb-2 m-2">
                            <div class="flex-grow">
                                <h4>
                                    <?= htmlspecialchars($task['nameTask'] ?? 'Sin nombre') . " " 
                                    . htmlspecialchars($task['description'] ?? 'Sin descripción')  ?>
                                </h4>
                            </div>
                            <div class="flex space-x-2">
                                <div class="w-20 h-16 border-4 border-[#BFE3F9] flex items-center justify-center rounded">
                                    <h2> 
                                        <?= htmlspecialchars($task['startDate'] ?? '') ?>
                                    </h2>
                                </div>
                                <div class="w-20 h-16 border-4 border-[#BFE3F9] flex items-center justify-center rounded">
                                    <h2> 
                                        <?= htmlspecialchars($task['endDate'] ?? '') ?>
                                    </h2>
                                </div>
                                <a href="<?php echo $this->baseUrl() ?>/tasks/delete/<?php echo $task['id'] ?>" class="text-red-500 hover:underline">
                                    Eliminar
                                </a>
                                <a href="<?php echo $this->baseUrl() ?>/tasks/update/<?php echo $task['id'] ?>" class="text-blue-500 hover:underline">
                                    Editar
                                </a>
                                
                                
 
                            </div>
                            
                        </div>
                            
                    <?php endforeach; ?>
                        <div class="mt-8 flex justify-center">
                            
                                
                        </div>
                </div>
               
            <?php else: ?>
                <p class="text-center text-gray-500 py-10">No hay tareas registradas.</p>
                
            <?php endif; ?>
         
            
        </div>
</main>
</section>