<?php

$allTasks = $this->allTasks;

arsort($allTasks);

?>

<div class="container mx-auto">
  <div class="relative overflow-x-auto shadow-md sm:rounded-lg">
    <div class="flex items-center justify-between flex-column flex-wrap md:flex-row space-y-4 md:space-y-0 pb-4 bg-white dark:bg-gray-900">
      <table class="w-full text-sm text-left rtl:text-right text-gray-500 dark:text-gray-400">
        <thead class="text-xs text-gray-700 uppercase bg-gray-50 dark:bg-gray-700 dark:text-gray-400">
          <tr>
            <th scope="col" class="px-6 py-3">
              Task ID
            </th>
            <th scope="col" class="px-6 py-3">
              Task Name
            </th>
            <th scope="col" class="px-6 py-3">
              Username
            </th>
            <th scope="col" class="px-6 py-3">
              Created Time
            </th>
            <th scope="col" class="px-6 py-3">
              Completed Time
            </th>

            <th scope="col" class="px-6 py-3">
              Status
            </th>
            <th scope="col" class="px-6 py-3">
              Action
            </th>
          </tr>
        </thead>
        <tbody>
          <?php foreach ($allTasks as $task) : ?>
            <tr class="bg-white border-b dark:bg-gray-800 dark:border-gray-700 hover:bg-gray-50 dark:hover:bg-gray-600">
              <td class="px-6 py-4">
                <?php echo $task->id; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->name; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->username; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->create_time; ?>
              </td>
              <td class="px-6 py-4">
                <?php echo $task->completed_time ?? 'Not completed'; ?>
              </td>

              <td class="px-6 py-4">
                <?php echo $task->status; ?>
              </td>
              <td class="px-6 py-4">
                <a href="/task/destroy/<?php echo $task->id; ?>" class="font-medium text-blue-600 dark:text-blue-500 hover:underline">Eliminar Tarea</a>
              </td>
            </tr>
          <?php endforeach; ?>
        </tbody>
      </table>
    </div>
  </div>
