<!DOCTYPE html>
<html lang="es">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>The task creat</title>
</head>
<body>
    <form method="POST" action="<?php echo $this->baseUrl(); ?>/tasksCreate">
        <div class="from-gruop-create">
            <label for="namaTask">NameTask</label>
            <input type="text" id="namaTask" name="namaTask" class="from-gruop-create" required>
        </div>

        <div class="from-gruop-create">
            <label for="taskStatus">TaskStatus</label>
            <select id="taskStatus" name="taskStatus">
                <option value="pending">PENDING</option>
                <option value="in_progress">IN_PROGRESS</option>
                <option value="completed">COMPLETED</option>
            </select>
        </div>

        <button type="submit">Crear Tarea</button>
    </form>
</body>
</html>file:///C:/xampp/htdocs/ITA-FS-PHP-Developers/app/views/scripts/task/taskCreate.phtml