<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Editar Id tarea</title>
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.css"  rel="stylesheet" />
</head>
<body>
<section class="h-screen min-h-screen bg-center bg-no-repeat bg-cover bg-[url('https://flowbite.s3.amazonaws.com/docs/jumbotron/conference.jpg')] bg-gray-700 bg-blend-multiply">
<div class="px-4 mx-auto max-w-screen-xl text-center py-8 lg:py-12">    
   
<h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl text-center">Editar tarea</h1>
<p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48 text-center">Introduzca el Id de la tarea que deseas editar </p>
</div>

<form action="<?php echo WEB_ROOT; ?>/updateId" method="POST" class="max-w-md mx-auto">
<div style="display: flex; justify-content: center; align-items: center;">
    <input type="number" name="task_id" value="<?php echo $task['id']; ?>" required />
    <a href="<?php echo WEB_ROOT ?>/update/<?php echo $task['id']; ?>">
    <button type="submit" class="text-white bg-blue-700 hover:bg-blue-800 focus:ring-4 focus:outline-none focus:ring-blue-300 font-medium rounded-lg text-sm w-full sm:w-auto px-5 py-2.5 text-center dark:bg-blue-600 dark:hover:bg-blue-700 dark:focus:ring-blue-800">Editar tarea</button>
    </div>
</form>

</body>
</html>