
<section class="create-form">
    <h1>update Task</h1>
    
    <form action="<?php echo $this->baseUrl();?>/tasks/update/<?php echo $this->task['id'];?>" method="POST">
      
         <div class="form-group">
                <label for="nameTask">Task Name*</label>
                <input type="text" id="nameTask" name="nameTask" class="form-control" required>
            </div>
            <div class="form-group">
                <label for="taskStatus">Status</label>
                <select id="taskStatus" name="taskStatus" class="form-control">
                    <option value="pending">Pending</option>
                    <option value="in_progress">In Progress</option>
                    <option value="completed">Completed</option>
                </select>
            </div>
            <div class="form-group">
                <label for="description">Description</label>
                <textarea id="description" name="description" rows="4" class="form-control"></textarea>
            </div>

            <div class="form-group">
                <label for="startDate">Start Date*</label>
                <input type="date" id="startDate" name="startDate" class="form-control" required>
            </div>

            <div class="form-group">
                <label for="endDate">End Date*</label>
                <input type="date" id="endDate" name="endDate" class="form-control">
            </div>
          

            <button type="submit">update Task</button>
        
    </form>
</section>
