<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Eliminar tarea</title>
    <link href="https://cdn.jsdelivr.net/npm/flowbite@2.5.1/dist/flowbite.min.css"  rel="stylesheet" />
</head>
<body>
<section class="h-screen min-h-screen bg-center bg-no-repeat bg-cover bg-[url('https://flowbite.s3.amazonaws.com/docs/jumbotron/conference.jpg')] bg-gray-700 bg-blend-multiply">
<div class="px-4 mx-auto max-w-screen-xl text-center py-8 lg:py-12">    
   
<h1 class="mb-4 text-4xl font-extrabold tracking-tight leading-none text-white md:text-5xl lg:text-6xl text-center">Eliminar tarea</h1>
<p class="mb-8 text-lg font-normal text-gray-300 lg:text-xl sm:px-16 lg:px-48 text-center">Introduzca el Id de la tarea que deseas eliminar </p>
</div>

<form action="<?php echo WEB_ROOT; ?>/updateId" method="POST">
    <label for="task_id">Ingrese el ID de la tarea a editar:</label>
    <input type="number" name="task_id" id="task_id" required />
    <button type="submit">Editar tarea</button>
</form>

</body>
</html>